### PR TITLE
Doc styling improvements

### PR DESCRIPTION
**Pull request by ultmaster**
Will improve css/js of docs here.

### CODE REVIEW

**Comment by matluster** [comment]
* Hide navigation bar sometimes to avoid too much "Neural Network Intelligence".

**Comment by matluster** [comment]
* Code padding is too small.

**Comment by matluster** [comment]
Enable a new theme.

**Comment by matluster** [comment]
* Improved TOC on mobile

image

**Comment by matluster** [comment]
* Adopt new fonts.

**Comment by matluster** [comment]
* New table style

image

* New heading style

image

**Comment by matluster** [comment]
Update on-this-page style

image

**Comment by matluster** [comment]
New icons:

image

**Review by QuanluZhang — APPROVED** [review]

**Review by J-shang — APPROVED** [review]

**Pull request merged**
