### PR TITLE
[fix issue#1332] Double check for trial does not have final result in webui

### PR DESCRIPTION
**Pull request by lvybriage**
#1332

### CODE REVIEW

**Comment by suiguoxin** [comment]
@ultmaster

**Comment by ultmaster** [comment]
I'm kind of confused. The bug seems to be fixed, but the interface looks like this in case there is no final result.

image

As you see, the default metrics in the bottom shows FINAL (but I didn't submit FINAL result); so if it is FINAL for real, why is it not shown on the hyper-parameter chart?

To reproduce this test, you only need to comment one line here and rerun MNIST as instructed: https://github.com/microsoft/nni/blob/a5fa235190c54f840fdb82b31ca26e1800e8d465/examples/trials/mnist/mnist.py#L207

Maybe I made some mistake; contact me if needed.

**Comment by lvybriage** [comment]
@ultmaster I'll continue to fix this confuse in detail table. If trial's status is succeed, and it haven't final result, will show that xxx (LATEST).

**Comment by lvybriage** [comment]
image

**Comment by ultmaster** [comment]
Issue fixed. @suiguoxin

**Pull request merged**
