### PR TITLE
Support dumplicate tensor in the tuple unpack

### PR DESCRIPTION
**Pull request by zheng-ningxin**
The input may be reused in the Tuple_constuct node,  for example: ['input1', 'input1', 'input2'].
In this case node.inputs will be ['input1', 'input2'] and trigger the assert assert len(node.inputs) == len(list(last_cpp.inputs())), errmsg.
So we use the cpp_node to get the debugName of the inputs.

### CODE REVIEW

**Comment by mwsunshine** [comment]
hi, ningxin,

I am wondering when will this bug be fixed according to your schedule? Meanwhile, will you release any kind of notification once it is fixed?

**Comment by zheng-ningxin** [comment]
> hi, ningxin,
> 
> I am wondering when will this bug be fixed according to your schedule? Meanwhile, will you release any kind of notification once it is fixed?
I guess this PR will be merged in a week and I'll send you a message once merged.

**Comment by mwsunshine** [comment]
> > hi, ningxin,
> > I am wondering when will this bug be fixed according to your schedule? Meanwhile, will you release any kind of notification once it is fixed?
> 
> @mwsunshine I guess this PR will be merged in a week and I'll send you a message once merged.

COOL!
Waiting for your message! So What I should do is to upgrade my nni to the latest version and try to prune the model once again?

**Review by QuanluZhang — APPROVED** [review]

**Review by J-shang — APPROVED** [review]

**Comment by mwsunshine** [comment]
> > hi, ningxin,
> > I am wondering when will this bug be fixed according to your schedule? Meanwhile, will you release any kind of notification once it is fixed?
> 
> @mwsunshine I guess this PR will be merged in a week and I'll send you a message once merged.

hi, ningxin,

I installed the latest nni via source code today, but the error remains. Is it fixed in the latest version? Or I still need to wait for a period of time.

**Pull request merged**
