### PR TITLE
Fix table sort issue

### PR DESCRIPTION
**Pull request by lvybriage**
Fix issue #1764

If a trial haven't any metric, it will always in the final row when we sort these trials.

### CODE REVIEW

**Comment by liuzhe-lz** [comment]
What's the root cause of this problem?
Is `a.accuracy` or `b.accuracy` undefined when it's expected to have value?

**Comment by lvybriage** [comment]
> What's the root cause of this problem?
> Is `a.accuracy` or `b.accuracy` undefined when it's expected to have value?

a.accuracy means trial's final metric. but default metric column also has intermediate result.

**Comment by lvybriage** [comment]
> What's the root cause of this problem?
> Is `a.accuracy` or `b.accuracy` undefined when it's expected to have value?

a.accuracy means trial's final metric. but default metric column also has intermediate result.

**Comment by lvybriage** [comment]
> What's the root cause of this problem?
> Is `a.accuracy` or `b.accuracy` undefined when it's expected to have value?

a.accuracy means trial's final metric. but default metric column also has intermediate result.

**Pull request merged**
