### PR TITLE
fix issue #2091

### PR DESCRIPTION
**Pull request by marsggbo**

### CODE REVIEW

**Comment by ultmaster** [comment]
I think this PR will induce risk that StackedLSTMCell doesn't work with batch_size > 1. But anyway, we only use this cell when batch_size is 1.

**Comment by ultmaster** [comment]
@marsggbo Can you add a comment suggesting that this cell only works with batch_size = 1?

**Comment by ultmaster** [comment]
Close #2091

**Comment by marsggbo** [comment]
this cell only works with batch_size = 1

**Comment by ultmaster** [comment]
@marsggbo Yes, I agree. But people who didn't read this PR might not be know that. Better add a note in the code.

**Comment by ultmaster** [comment]
thanks @QuanluZhang

**Pull request merged**
