### PR TITLE
Fix AdaptDL Intergration

### PR DESCRIPTION
**Pull request by hao-howard-zhang**
This PR fixed the AdaptDL integration with the recent changes on NNI master branch. Changes include:

- Mention AdaptDL in the main README
- Fix a typo in `setup.py`
- Rename `nni_trial_tool.trial_keeper` to `nni.tools.trial_tool.trial_keeper` because of the repo structure change
- Remove the line `config_file_name = experiment_dict[experiment_id]['fileName']` in `nni/tools/nnictl/tensorboard_utils.py:: start_tensorboard` because 1) looks like there is no `fileName` field in the dict any more, and 2) `config_file_name` is not used in that function.

Also, there is a change in master related to `codeDir` path parsing that breaks non-local job executions. [This change](https://github.com/microsoft/nni/blob/95f731e481913d1228ae4faa012a463ddced5208/nni%2Ftools%2Fnnictl%2Flauncher_utils.py#L73) will parse all the relative paths in the `config.yml` to absolute paths. If the trial is meant to be executed in a remote environment, `codeDir: .` will be parsed to the user's local path first and then sent to the remote cluster for execution. Hence, I changed the `codeDir` in the `config_adl.yml` to an absolute path in the docker container for now. I think other examples may have issues related to this as well.

cc. @SparkSnail @liuzhe-lz

### CODE REVIEW

**Comment by hao-howard-zhang** [comment]
One of the experiment failed in macos pipeline with error:
```
Traceback (most recent call last):
  File "nni_test/nnitest/naive_test.py", line 114, in <module>
    stop_experiment_test(args)
  File "nni_test/nnitest/naive_test.py", line 95, in stop_experiment_test
    wait_for_port_available(8990, 10)
  File "/Users/runner/work/1/s/test/nni_test/nnitest/utils.py", line 180, in wait_for_port_available
    raise RuntimeError(msg)
RuntimeError: port 8990 is not available in 10 seconds.
```

Do I need to worry about it, or it's just an intermittent issue and can be resolved by retrying?

**Comment by SparkSnail** [comment]
@scarlett2018 Should Chinese doc be updated?

**Comment by SparkSnail** [comment]
> @scarlett2018 Should Chinese doc be updated?

@hao-howard-zhang , Please revert Chinese doc change, NNI will update and check all of Chinese doc in a time interval, don't need to change this doc in individual PR.

**Comment by SparkSnail** [comment]
> This PR fixed the AdaptDL integration with the recent changes on NNI master branch. Changes include:
> 
> * Mention AdaptDL in the main README
> * Fix a typo in `setup.py`
> * Rename `nni_trial_tool.trial_keeper` to `nni.tools.trial_tool.trial_keeper` because of the repo structure change
> * Remove the line `config_file_name = experiment_dict[experiment_id]['fileName']` in `nni/tools/nnictl/tensorboard_utils.py:: start_tensorboard` because 1) looks like there is no `fileName` field in the dict any more, and 2) `config_file_name` is not used in that function.
> 
> Also, there is a change in master related to `codeDir` path parsing that breaks non-local job executions. [This change](https://github.com/microsoft/nni/blob/95f731e481913d1228ae4faa012a463ddced5208/nni%2Ftools%2Fnnictl%2Flauncher_utils.py#L73) will parse all the relative paths in the `config.yml` to absolute paths. If the trial is meant to be executed in a remote environment, `codeDir: .` will be parsed to the user's local path first and then sent to the remote cluster for execution. Hence, I changed the `codeDir` in the `config_adl.yml` to an absolute path in the docker container for now. I think other examples may have issues related to this as well.
> 
> cc. @SparkSnail @liuzhe-lz

@hao-howard-zhang  Generally, `codeDir` in NNI means local directory, not remote directory.  For example, in remote mode, when users create a new experiment, NNI will package `codeDir` folder, and copy this folder to remote machine. NNI will create a new experiment environment folder for NNI in remote machine automatically, and run command under this folder. In adl mode, this folder seems means path in docker container, you could add logic to avoid parse relative path in NNICTL when the platform is ADL.

**Comment by hao-howard-zhang** [comment]
> > @scarlett2018 Should Chinese doc be updated?
> 
> @hao-howard-zhang , Please revert Chinese doc change, NNI will update and check all of Chinese doc in a time interval, don't need to change this doc in individual PR.

Reverted.

**Comment by hao-howard-zhang** [comment]
> > This PR fixed the AdaptDL integration with the recent changes on NNI master branch. Changes include:
> > 
> > * Mention AdaptDL in the main README
> > * Fix a typo in `setup.py`
> > * Rename `nni_trial_tool.trial_keeper` to `nni.tools.trial_tool.trial_keeper` because of the repo structure change
> > * Remove the line `config_file_name = experiment_dict[experiment_id]['fileName']` in `nni/tools/nnictl/tensorboard_utils.py:: start_tensorboard` because 1) looks like there is no `fileName` field in the dict any more, and 2) `config_file_name` is not used in that function.
> > 
> > Also, there is a change in master related to `codeDir` path parsing that breaks non-local job executions. [This change](https://github.com/microsoft/nni/blob/95f731e481913d1228ae4faa012a463ddced5208/nni%2Ftools%2Fnnictl%2Flauncher_utils.py#L73) will parse all the relative paths in the `config.yml` to absolute paths. If the trial is meant to be executed in a remote environment, `codeDir: .` will be parsed to the user's local path first and then sent to the remote cluster for execution. Hence, I changed the `codeDir` in the `config_adl.yml` to an absolute path in the docker container for now. I think other examples may have issues related to this as well.
> > cc. @SparkSnail @liuzhe-lz
> 
> @hao-howard-zhang Generally, `codeDir` in NNI means local directory, not remote directory. For example, in remote mode, when users create a new experiment, NNI will package `codeDir` folder, and copy this folder to remote machine. NNI will create a new experiment environment folder for NNI in remote machine automatically, and run command under this folder. In adl mode, this folder seems means path in docker container, you could add logic to avoid parse relative path in NNICTL when the platform is ADL.

Thanks. I added a logic in `launcher_utils.py` to avoid parsing `codeDir` in adl mode.

**Review by SparkSnail — APPROVED** [review]

**Comment by hao-howard-zhang** [comment]
Hi @liuzhe-lz, could you take a look at this PR when you have time?

**Comment by hao-howard-zhang** [comment]
> Hi @liuzhe-lz, could you take a look at this PR when you have time?

Hi @SparkSnail, I'm not sure if @liuzhe-lz is available now. Could you help me ping him or find another approver?

**Review by liuzhe-lz — APPROVED** [review]

**Comment by htdp2542** [comment]
@hao-howard-zhang Could you please provide a working Dockerfile that you use to run the adl example?

**Comment by hao-howard-zhang** [comment]
> @hao-howard-zhang Could you please provide a working Dockerfile that you use to run the adl example?

No problem! I added the Dockerfile in this PR: https://github.com/microsoft/nni/pull/3176/commits/b512d09860641ded28116dcf1350fc4b5b93828a

**Pull request merged**
