### PR TITLE
Abstract class for automatic compression

### PR DESCRIPTION
**Pull request by MohamedAliRashad**
PR to track the addition of auto compression interface requested here #3385

### CODE REVIEW

**Comment by MohamedAliRashad** [comment]
We will need to discuss the attributes of the class and how it will work

**Comment by QuanluZhang** [comment]
> We will need to discuss the attributes of the class and how it will work

thanks for your contribution, feel free to post more detailed design. we will first discuss internally and provide more related information and design suggestions soon.

**Comment by J-shang** [comment]
Hi @MohamedAliRashad , we want to implement this feature in the next version, and I commit our basic idea about this. Include `MultiCompressor` which can specify the pruner and quantizer for each layer, and base on it `AutoCompressor` can auto change the pruner and quantizer to find their effect.

**Comment by J-shang** [comment]
The latest implementation is in #3627 and #3631, and this pr will be closed.

**Pull request closed without merging**
