### PR TITLE
merge latest master to dev-v2.0 (do not squash)

### PR DESCRIPTION
**Pull request by QuanluZhang**

### CODE REVIEW

**Comment by ultmaster** [comment]
I suggest merging via `git` locally rather than a PR. Or at least it shouldn't be squashed. "Squash and merge" will cause conflicts in future when merging back.

**Comment by chicm-ms** [comment]
Is this PR necessary?

**Comment by QuanluZhang** [comment]
> Is this PR necessary?

if we want to include new updates from master branch in dev-v2.0 in order to avoid possible merge conflict. Or some features depend on new features, bug fix in v1.9.

**Comment by chicm-ms** [comment]
> > Is this PR necessary?
> 
> if we want to include new updates from master branch in dev-v2.0 in order to avoid possible merge conflict. Or some features depend on new features, bug fix in v1.9.

It seems there is no any commit on dev-2.0 by now,  if you want merge now, you can just delete dev-2.0 and recreate it.

**Comment by QuanluZhang** [comment]
> > > Is this PR necessary?
> > 
> > 
> > if we want to include new updates from master branch in dev-v2.0 in order to avoid possible merge conflict. Or some features depend on new features, bug fix in v1.9.
> 
> It seems there is no any commit on dev-2.0 by now, if you want merge now, you can just delete dev-2.0 and recreate it.

sure, will do

**Pull request closed without merging**
