### PR TITLE
example mnist was not compatible with tersorflowv2

### PR DESCRIPTION
**Pull request by xinshouke**
replace line 9  with tensorflow.compat.v1,the cause  was not able to  compatible with tersorflowv2

### CODE REVIEW

**Comment by liuzhe-lz** [comment]
This change will make it incompatible with tensorflow lower than 1.13.
We will discuss how to resolve the issue soon.

**Comment by xinshouke** [comment]
> This change will make it incompatible with tensorflow lower than 1.13.
> We will discuss how to resolve the issue soon.

Oh,maybe I thought it must support tensorflow v2 while using python >= 3.5...I rushed advance a little.

**Comment by liuzhe-lz** [comment]
I totally agree it should support tensorflow v2.
But we want to support lower versions at the same time...

**Comment by liuzhe-lz** [comment]
We have added a [TFv2 example](https://github.com/microsoft/nni/tree/master/examples/trials/mnist-tfv2) and we are working on using v2 as default.

**Pull request closed without merging**
