### PR TITLE
Added WeChat link

### PR DESCRIPTION
**Pull request by Rishit-dagli**
Added WeChat link in the text for better usability

### CODE REVIEW

**Comment by liuzhe-lz** [comment]
Seems there's already a QR code. Maybe we can add href on the QR code image?

**Comment by Rishit-dagli** [comment]
@liuzhe-lz That seemed like a better idea I have edited the code to do the same. You are requested to review this.

**Comment by Jie-Yuan** [comment]
Added WeChat link in the text for better usability

**Comment by liuzhe-lz** [comment]
Sorry but after some testing we find hyperlink does not work.
WeChat only accepts QR code. Accessing the URL directly will lead to a redirect.

**Pull request closed without merging**
